name: Debug gpg

env:
  PGP_SECRET: ${{ secrets.PGP_SECRET }}

jobs:
  build:
    name: Import key
    strategy:
      matrix:
        os: [ubuntu-latest]
        scala: [3.0.0-M2]
        java: [adopt@1.11]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Import signing key
        run: echo $PGP_SECRET | base64 -d | gpg --import --verbose

